### PR TITLE
Camera support

### PR DESCRIPTION
**Pull request by edekeijzer**
Just dropping this here as a draft, to let you know what's cooking. I have just filed a [pull request](https://github.com/OctoPrint/OctoPrint-MQTT/pull/98) for the MQTT plugin to allow publishing raw data. If this gets accepted, we have the possibility to post images to a topic, which can then be announced to HA as an MQTT camera. I've hooked this to the event for taking a timelapse snapshot so you get that image in your HA automatically, as well as a topic where a request can be made to take a snapshot - I still have to build a nice button around that though.

### CODE REVIEW

**Comment by edekeijzer** [comment]
The Octoprint team was quite fast with merging, the raw_data switch was already released. I also added the camera_snapshot switch to the code and tested it.

**Comment by cmroche** [comment]
Hi @edekeijzer Sorry I missed this review request... I'll try to look through it over the weekend.

**Comment by edekeijzer** [comment]
> Hi @edekeijzer Sorry I missed this review request... I'll try to look through it over the weekend.

Thanks, no problem. After this I've got another one coming ;) My PR for helpers/hooks in PSUControl has been merged so I can start testing on the production version of PSUControl and then send you the updated version which publishes the PSU switch in Home Assistant.

**Comment by cmroche** [comment]
@edekeijzer LGTM, can you please resolve conflicts and I'll merge.

**Comment by edekeijzer** [comment]
Just merged your on_printer_connect code into my branch and pushed it.

**Comment by cmroche** [comment]
Thanks, will be in the next version, soon.

**Pull request merged**
